version: "2"

services:
  nginx-ws:
    build: ./nginx-ws
    ports:
      - '80:80'
      - '443:443'
    networks:
      - vpnws
    volumes:
      - /tmp/alpaca/www/vhosts/:/var/www/vhosts/
    environment:
      DOMAINS: 'caonima.com'
      STAGE: 'local'

  alpaca:
    build: ./alpaca
    privileged: true
    networks:
      - vpnws

networks:
  vpnws:
    driver: bridge
