version: "2"

services:
  nginx-ws:
    build: ./nginx-ws
    ports:
      - '80:80'
      - '443:443'
    networks:
      - vpnws
    volumes:
      - /tmp/aiovpn/www/vhosts/:/var/www/vhosts/
    links:
      - aiovpn
    environment:
      USE_HTPASSWD_FILE: 'false'
      VPN_USERNAME: 'alpaca'
      VPN_PASSWORD: 'caonima'
      VPN_URL: '/aiovpn'
      DOMAINS: 'caonima.com'
      STAGE: 'staging'

  aiovpn:
    build: ./aiovpn
    privileged: true
    networks:
      - vpnws
    environment:
      PRIVATE_IP: '10.18.1.1/24'

networks:
  vpnws:
    driver: bridge
